version: "3.7"

services:
  app:
    build:
      context: app
      target: app-dev
    command: npm run dev
    entrypoint: ''
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
